//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOOP1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public int ISN { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public System.DateTime DATEBIRTH { get; set; }
    }
}
